#!/usr/bin/env bash

set -euo pipefail

# Initialise required variables

BATTERY="$(jq -r .battery "${HOME}/.bin/config.json")"
BATTERY_SYSFS="/sys/class/power_supply/${BATTERY}"

BATTERY_CAPACITY="$(cat "${BATTERY_SYSFS}/capacity")"
BATTERY_STATUS="$(cat "${BATTERY_SYSFS}/status")"

# --icon: Print battery status icon
# --capacity: Get battery capacity
# --status: Get battery status
case "${1}" in
"--icon")
    ICON=""
    CH_ICON=""

    case "$(((BATTERY_CAPACITY / 10)))" in
    0)
        ICON=""
        CH_ICON=""
        ;;
    1)
        ICON=""
        CH_ICON="" # No 10% charging found
        ;;
    2)
        ICON=""
        CH_ICON=""
        ;;
    3)
        ICON=""
        CH_ICON=""
        ;;
    4)
        ICON=""
        CH_ICON=""
        ;;
    5)
        ICON=""
        CH_ICON=""
        ;;
    6)
        ICON=""
        CH_ICON=""
        ;;
    7)
        ICON=""
        CH_ICON=""
        ;;
    8)
        ICON=""
        CH_ICON=""
        ;;
    9)
        ICON=""
        CH_ICON=""
        ;;
    10)
        ICON=""
        CH_ICON=""
        ;;
    *)
        ICON=""
        CH_ICON=""
        ;;
    esac

    if [[ "${BATTERY_STATUS}" == "Discharging" ]]; then
        echo -n "${ICON}"
    else
        echo -n "${CH_ICON}"
    fi
    ;;
"--capacity")
    echo "${BATTERY_CAPACITY}"
    ;;
"--state")
    echo "${BATTERY_STATUS}"
    ;;
*)
    echo "Invalid arguments!"
    exit 1
    ;;
esac
